package dc

import "github.com/flostadler/name-generator/pkg/randomizer"

var(
	characters = [...] string {
		"Alfred Pennyworth",
		"Amanda Waller",
		"Amethyst",
		"Anarky",
		"Anti-Monitor",
		"Aquaman",
		"Ares",
		"Arsenal",
		"Atlanna",
		"Atom",
		"Atrocitus",
		"Bane",
		"Batgirl",
		"Batman",
		"Batwoman",
		"Beast Boy",
		"Big Barda",
		"Birds Of Prey",
		"Bizarro",
		"Black Adam",
		"Black Canary",
		"Black Lightning",
		"Black Manta",
		"Blue Beetle",
		"Booster Gold",
		"Brainiac",
		"Captain Boomerang",
		"Captain Cold",
		"Captain Marvel Jr.",
		"Catwoman",
		"Clayface",
		"Commissioner James Gordon",
		"Cyborg",
		"Damian Wayne",
		"Damien Darhk",
		"Darkseid",
		"Dead Boy Detectives",
		"Deadman",
		"Deadshot",
		"Deathstroke",
		"Deimos",
		"Doctor Sivana",
		"Donna Troy",
		"Doom Patrol",
		"Doomsday",
		"El Diablo",
		"Enchantress",
		"Eve Coffin",
		"Fbp: Federal Bureau Of Physics",
		"Firestorm",
		"Gorilla Grodd",
		"Green Arrow",
		"Green Lantern",
		"Green Lantern Corps",
		"H.I.V.E.",
		"Harley Quinn",
		"Harvey Bullock",
		"Hawk And Dove",
		"Hawkgirl",
		"Hawkman",
		"Heat Wave",
		"Hinterkind",
		"Jay Garrick",
		"Jesse Custer",
		"Jimmy Olsen",
		"John Constantine",
		"Joker",
		"Justice League",
		"Katana",
		"Killer Croc",
		"Killer Frost",
		"Krypto",
		"Lex Luthor",
		"Lobo",
		"Lois Lane",
		"Lucifer",
		"Lucius Fox",
		"Martian Manhunter",
		"Mary Marvel",
		"Maxwell Lord",
		"Mera",
		"Midnighter",
		"Mister Freeze",
		"Mister Miracle",
		"Mister Terrific",
		"Morpheus",
		"Nereus",
		"New Gods",
		"Nightwing",
		"Nuidis Vulko",
		"Ocean Master",
		"Pandora",
		"Penguin",
		"Plastic Man",
		"Poison Ivy",
		"Ra'S Al Ghul",
		"Raven",
		"Reverse-Flash",
		"Rick Flag",
		"Riddler",
		"Rip Hunter",
		"Robin",
		"Scarecrow",
		"Seven Deadly Sins",
		"Shazam",
		"Shazam Family",
		"Sinestro",
		"Solomon Grundy",
		"Starfire",
		"Stephen Shin",
		"Steppenwolf",
		"Steve Trevor",
		"Suicide Squad",
		"Superboy",
		"Supergirl",
		"Superman",
		"Swamp Thing",
		"Tawky Tawny",
		"Telos",
		"The Cheetah",
		"The Flash",
		"The Phantom Stranger",
		"Thomas Curry",
		"Titans",
		"Trigon",
		"Two-Face",
		"Vandal Savage",
		"Vixen",
		"Watchmen",
		"Wizard Shazam",
		"Wonder Woman",
		"Zatanna",
		"Zod",
		"Zoom",
	}
)

func Generate() string {
	return randomizer.GetRandom(characters[:])
}
